version: '3.8'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 1724
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "1724:1724"
    environment:
      AWS_ACCESS_KEY_ID: "${ACCESS_KEY}"
      AWS_SECRET_ACCESS_KEY: "${SECRET_ACCESS_KEY}"
      DATABASE_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
